server:
  port: 8082
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
spring:
  application:
    name: GREET_SERVICE
message: Hi this is User.Mesage from app.yml 